#!/bin/bash

BASE_DIR=$( realpath $( dirname "${BASH_SOURCE[0]}" )/../ )
source "$BASE_DIR/.bin/lib/common.sh"
setRoot

pushd "$ROOT_PATH" 2>&1 >/dev/null

echo "Running isort..."
isort -c .
exit_code=$?
echo

echo "Running black..."
black --check .
test $? -eq 0 -a $exit_code -eq 0
exit_code=$?
echo

# echo "Running ruff..."
# ruff check --preview .
# test $? -eq 0 -a $exit_code -eq 0
# exit_code=$?
# echo

echo "Running mypy..."
mypy .
test $? -eq 0 -a $exit_code -eq 0
exit_code=$?
echo

popd 2>&1 >/dev/null

exit $exit_code
